### ISSUE TITLE
nixpkgs init

### ISSUE THREAD

**Issue by heywoodlh** [MeF0504/vim-pets#6]
I added vim-pets to Nixpkgs in order to be able to use the plugin with Vim managed with [Nix](https://nixos.org): https://github.com/NixOS/nixpkgs/pull/260055

Please let me know if this is undesired. :smile:

Thanks for the great plugin!

**Comment by MeF0504** [comment]
Sorry for the late reply.
I think it's no problem to add vim-pets to Nixpkgs.
Thank you for letting me know and adding my plugin.
